version: '3.8'

services:
  flask-app:
    build: .
    container_name: secure-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=supersecretkey
    volumes:
      - .:/app
    command: ["python", "app.py"]
